version: '3.0'

expectations:
  population_size: 1000000

actions:

  extract_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all
    outputs:
      highly_sensitive:
        cohort: output/input_all.csv
        
  generate_flowchartdata:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_all_flow_chart.csv
        
  flow_chart_all:
    run: r:latest -e 'rmarkdown::render("analysis/R/study_definition_all_flow_chart.Rmd", output_dir="/workspace/output")'
    needs: [generate_flowchartdata]
    outputs:
      moderately_sensitive:
        html: output/study_definition_all_flow_chart.html

  data_process_all:
    run: r:latest analysis/R/data_process_all.R
    needs: [extract_all]
    outputs:
      highly_sensitive:
        data1: output/data/data_all.rds
        data2: output/data/data_long_vax_dates.rds
        data3: output/data/data_long_admission_dates.rds
        data4: output/data/data_long_pr_probable_covid_dates.rds
        data5: output/data/data_long_pr_suspected_covid_dates.rds


  data_properties_all:
    run: r:latest analysis/R/data_properties.R output/data/data_all.rds output/data_properties
    needs: [data_process_all]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_all*.txt

  data_define_cohorts:
    run: r:latest analysis/R/data_define_cohorts.R
    needs: [data_process_all]
    outputs:
      highly_sensitive:
        data: output/data/data_cohorts.rds
      moderately_sensitive:
        metadata: output/data/metadata_cohorts.rds
        formula: output/data/list_formula.rds



#######################################
#######################################
  ## VE in over 80s (over80s)
#######################################
#######################################

  data_stset_over80s:
    run: r:latest analysis/R/data_stset.R over80s
    needs: [data_define_cohorts, data_process_all]
    outputs:
      highly_sensitive:
        data: output/over80s/data/data_*.rds

  data_properties_over80s_fixed:
    run: r:latest analysis/R/data_properties.R output/over80s/data/data_wide_fixed.rds output/over80s/data_properties
    needs: [data_stset_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/over80s/data_properties/data_wide_fixed*.txt

  data_properties_over80s_tte:
    run: r:latest analysis/R/data_properties.R output/over80s/data/data_wide_tte.rds output/over80s/data_properties
    needs: [data_stset_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/over80s/data_properties/data_wide_tte*.txt

  # descr_eventsperday_over80s:
  #   run: r:latest analysis/R/plot_outcomes_per_day.R over80s postest
  #   needs: [data_define_cohorts, data_stset_over80s]
  #   outputs:
  #     moderately_sensitive:
  #       datasummary: output/over80s/postest/descr/events*.svg

  descr_table1_over80s:
    run: r:latest analysis/R/table1.R over80s
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      moderately_sensitive:
        table1: output/over80s/descr/tables/table*

  descr_events_over80s:
    run: r:latest analysis/R/plot_status_over_time.R over80s
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      moderately_sensitive:
        plots: output/over80s/descr/plots/*.svg


#######################################
 ## OVERALL MODELS: vax1 only (ignores second dose)
#######################################

## any vaccine

  models_msm_over80s_any_all_dose1:
    run: r:latest analysis/R/model_msm_dose1.R over80s postest any all
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/any/all/*/model*.rds
        data: output/over80s/postest/any/all/*/data_weights.rds
      moderately_sensitive:
        strata: output/over80s/postest/any/all/strata_vector.rds
        weights: output/over80s/postest/any/all/*/weights*

  report_msm_over80s_any_all_dose1:
    run: r:latest analysis/R/report_msm_dose1.R over80s postest any all
    needs: [data_define_cohorts, models_msm_over80s_any_all_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/any/all/forest*.svg
        tables: output/over80s/postest/any/all/*.csv


## pfizer vaccine
  models_msm_over80s_pfizer_all_dose1:
    run: r:latest analysis/R/model_msm_dose1.R over80s postest pfizer all
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/pfizer/all/*/model*.rds
        data: output/over80s/postest/pfizer/all/*/data_weights.rds
      moderately_sensitive:
        strata: output/over80s/postest/pfizer/all/strata_vector.rds
        weights: output/over80s/postest/pfizer/all/*/weights*

  report_msm_over80s_pfizer_all_dose1:
    run: r:latest analysis/R/report_msm_dose1.R over80s postest pfizer all
    needs: [data_define_cohorts, models_msm_over80s_pfizer_all_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/pfizer/all/forest*.svg
        tables: output/over80s/postest/pfizer/all/*.csv


## az vaccine

  models_msm_over80s_az_all_dose1:
    run: r:latest analysis/R/model_msm_dose1.R over80s postest az all
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/az/all/*/model*.rds
        data: output/over80s/postest/az/all/*/data_weights.rds
      moderately_sensitive:
        strata: output/over80s/postest/az/all/strata_vector.rds
        weights: output/over80s/postest/az/all/*/weights*


  report_msm_over80s_az_all_dose1:
    run: r:latest analysis/R/report_msm_dose1.R over80s postest az all
    needs: [data_define_cohorts, models_msm_over80s_az_all_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/az/all/forest*.svg
        tables: output/over80s/postest/az/all/*.csv


#######################################
## SUBGROUPS
#######################################

## sex

  models_msm_over80s_any_sex_dose1:
    run: r:latest analysis/R/model_msm_dose1.R over80s postest any sex
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/any/sex/*/model*.rds
        data: output/over80s/postest/any/sex/*/data_weights.rds
      moderately_sensitive:
        strata: output/over80s/postest/any/sex/strata_vector.rds
        weights: output/over80s/postest/any/sex/*/weights*

  report_msm_over80s_any_sex_dose1:
    run: r:latest analysis/R/report_msm_dose1.R over80s postest any sex
    needs: [data_define_cohorts, models_msm_over80s_any_sex_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/any/sex/forest*.svg
        tables: output/over80s/postest/any/sex/*.csv


## pfizer vaccine
  models_msm_over80s_pfizer_sex_dose1:
    run: r:latest analysis/R/model_msm_dose1.R over80s postest pfizer sex
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/pfizer/sex/*/model*.rds
        data: output/over80s/postest/pfizer/sex/*/data_weights.rds
      moderately_sensitive:
        strata: output/over80s/postest/pfizer/sex/strata_vector.rds
        weights: output/over80s/postest/pfizer/sex/*/weights*

  report_msm_over80s_pfizer_sex_dose1:
    run: r:latest analysis/R/report_msm_dose1.R over80s postest pfizer sex
    needs: [data_define_cohorts, models_msm_over80s_pfizer_sex_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/pfizer/sex/forest*.svg
        tables: output/over80s/postest/pfizer/sex/*.csv


## az vaccine

  models_msm_over80s_az_sex_dose1:
    run: r:latest analysis/R/model_msm_dose1.R over80s postest az sex
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/az/sex/*/model*.rds
        data: output/over80s/postest/az/sex/*/data_weights.rds
      moderately_sensitive:
        strata: output/over80s/postest/az/sex/strata_vector.rds
        weights: output/over80s/postest/az/sex/*/weights*


  report_msm_over80s_az_sex_dose1:
    run: r:latest analysis/R/report_msm_dose1.R over80s postest az sex
    needs: [data_define_cohorts, models_msm_over80s_az_sex_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/az/sex/forest*.svg
        tables: output/over80s/postest/az/sex/*.csv



#######################################
#######################################
  ## VE in 70s (in70s)
#######################################
#######################################


  data_stset_in70s:
    run: r:latest analysis/R/data_stset.R in70s
    needs: [data_define_cohorts, data_process_all]
    outputs:
      highly_sensitive:
        data: output/in70s/data/data_*.rds

  data_properties_in70s_fixed:
    run: r:latest analysis/R/data_properties.R output/in70s/data/data_wide_fixed.rds output/in70s/data_properties
    needs: [data_stset_in70s]
    outputs:
      moderately_sensitive:
        datasummary: output/in70s/data_properties/data_wide_fixed*.txt

  data_properties_in70s_tte:
    run: r:latest analysis/R/data_properties.R output/in70s/data/data_wide_tte.rds output/in70s/data_properties
    needs: [data_stset_in70s]
    outputs:
      moderately_sensitive:
        datasummary: output/in70s/data_properties/data_wide_tte*.txt

  # descr_eventsperday_in70s:
  #   run: r:latest analysis/R/plot_outcomes_per_day.R in70s postest
  #   needs: [data_define_cohorts, data_stset_in70s]
  #   outputs:
  #     moderately_sensitive:
  #       datasummary: output/in70s/postest/descr/events*.svg

  descr_table1_in70s:
    run: r:latest analysis/R/table1.R in70s
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      moderately_sensitive:
        table1: output/in70s/descr/tables/table*

  descr_events_in70s:
    run: r:latest analysis/R/plot_status_over_time.R in70s
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      moderately_sensitive:
        plots: output/in70s/descr/plots/*.svg


#######################################
 ## OVERALL MODELS: vax1 only (ignores second dose)
#######################################

## any vaccine

  models_msm_in70s_any_all_dose1:
    run: r:latest analysis/R/model_msm_dose1.R in70s postest any all
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/any/all/*/model*.rds
        data: output/in70s/postest/any/all/*/data_weights.rds
      moderately_sensitive:
        strata: output/in70s/postest/any/all/strata_vector.rds
        weights: output/in70s/postest/any/all/*/weights*

  report_msm_in70s_any_all_dose1:
    run: r:latest analysis/R/report_msm_dose1.R in70s postest any all
    needs: [data_define_cohorts, models_msm_in70s_any_all_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/any/all/forest*.svg
        tables: output/in70s/postest/any/all/*.csv


## pfizer vaccine
  models_msm_in70s_pfizer_all_dose1:
    run: r:latest analysis/R/model_msm_dose1.R in70s postest pfizer all
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/pfizer/all/*/model*.rds
        data: output/in70s/postest/pfizer/all/*/data_weights.rds
      moderately_sensitive:
        strata: output/in70s/postest/pfizer/all/strata_vector.rds
        weights: output/in70s/postest/pfizer/all/*/weights*

  report_msm_in70s_pfizer_all_dose1:
    run: r:latest analysis/R/report_msm_dose1.R in70s postest pfizer all
    needs: [data_define_cohorts, models_msm_in70s_pfizer_all_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/pfizer/all/forest*.svg
        tables: output/in70s/postest/pfizer/all/*.csv


## az vaccine

  models_msm_in70s_az_all_dose1:
    run: r:latest analysis/R/model_msm_dose1.R in70s postest az all
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/az/all/*/model*.rds
        data: output/in70s/postest/az/all/*/data_weights.rds
      moderately_sensitive:
        strata: output/in70s/postest/az/all/strata_vector.rds
        weights: output/in70s/postest/az/all/*/weights*


  report_msm_in70s_az_all_dose1:
    run: r:latest analysis/R/report_msm_dose1.R in70s postest az all
    needs: [data_define_cohorts, models_msm_in70s_az_all_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/az/all/forest*.svg
        tables: output/in70s/postest/az/all/*.csv


#######################################
## SUBGROUPS
#######################################

## sex

  models_msm_in70s_any_sex_dose1:
    run: r:latest analysis/R/model_msm_dose1.R in70s postest any sex
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/any/sex/*/model*.rds
        data: output/in70s/postest/any/sex/*/data_weights.rds
      moderately_sensitive:
        strata: output/in70s/postest/any/sex/strata_vector.rds
        weights: output/in70s/postest/any/sex/*/weights*

  report_msm_in70s_any_dose1:
    run: r:latest analysis/R/report_msm_dose1.R in70s postest any sex
    needs: [data_define_cohorts, models_msm_in70s_any_sex_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/any/sex/forest*.svg
        tables: output/in70s/postest/any/sex/*.csv


## pfizer vaccine
  models_msm_in70s_pfizer_sex_dose1:
    run: r:latest analysis/R/model_msm_dose1.R in70s postest pfizer sex
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/pfizer/sex/*/model*.rds
        data: output/in70s/postest/pfizer/sex/*/data_weights.rds
      moderately_sensitive:
        strata: output/in70s/postest/pfizer/sex/strata_vector.rds
        weights: output/in70s/postest/pfizer/sex/*/weights*

  report_msm_in70s_pfizer_sex_dose1:
    run: r:latest analysis/R/report_msm_dose1.R in70s postest pfizer sex
    needs: [data_define_cohorts, models_msm_in70s_pfizer_sex_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/pfizer/sex/forest*.svg
        tables: output/in70s/postest/pfizer/sex/*.csv


## az vaccine

  models_msm_in70s_az_sex_dose1:
    run: r:latest analysis/R/model_msm_dose1.R in70s postest az sex
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/az/sex/*/model*.rds
        data: output/in70s/postest/az/sex/*/data_weights.rds
      moderately_sensitive:
        strata: output/in70s/postest/az/sex/strata_vector.rds
        weights: output/in70s/postest/az/sex/*/weights*


  report_msm_in70s_az_sex_dose1:
    run: r:latest analysis/R/report_msm_dose1.R in70s postest az sex
    needs: [data_define_cohorts, models_msm_in70s_az_sex_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/az/sex/forest*.svg
        tables: output/in70s/postest/az/sex/*.csv


