version: '3.0'

expectations:
  population_size: 10000

actions:

  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/notebooks/population_characteristics.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
  #
  #   needs: [generate_delivery_cohort]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/population_characteristics.html

  get_packages:
    run: r:latest analysis/R/export_package_names.R
    outputs:
      moderately_sensitive:
        cohort: output/available_packages.csv



## Descriptive info on vaccinated patients
  extract_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.csv

  data_process_vaccinated:
    run: r:latest analysis/R/data_process_vaccinated.R
    needs: [extract_vaccinated]
    outputs:
      highly_sensitive:
        cohort: output/data/data_vaccinated.rds

  data_properties_vaccinated:
    run: r:latest analysis/R/data_properties.R output/data/data_vaccinated.rds output/data_properties
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        summary: output/data_properties/data_vaccinated_colsummary.txt
        types: output/data_properties/data_vaccinated_coltypes.txt

  data_summarise:
    run: r:latest analysis/R/data_summarise.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        summary1: output/variable_summary/categorical.txt
        summary2: output/variable_summary/numeric.txt
        summary3: output/variable_summary/date.txt
        summarytables: output/variable_summary/tables/categorical_*.csv
        summarystats: output/summary_stats.json

  vaccine_tables:
    run: r:latest analysis/R/vaccine_type.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        tables: output/vaccine_type/tables/vaccine_type_*.csv

  tte_tables:
    run: r:latest analysis/R/tte_tables.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        tables: output/tte/tables/event_rates_*.csv

  tte_plots:
    run: r:latest analysis/R/tte_plots.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        plots: output/tte/figures/plot_*.svg


  ## VE in over 80s

  extract_over80s:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_over80s
    outputs:
      highly_sensitive:
        cohort: output/input_over80s.csv


  data_process_over80s:
    run: r:latest analysis/R/data_process_over80s.R
    needs: [extract_over80s]
    outputs:
      highly_sensitive:
        cohort: output/data/data_over80s.rds

  models_over80s:
    run: r:latest analysis/R/models_over80s.R
    needs: [data_process_over80s]
    outputs:
      moderately_sensitive:
        log: output/cox.txt
