version: '3.0'

expectations:
  population_size: 100000

actions:

  extract_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all
    outputs:
      highly_sensitive:
        cohort: output/input_all.csv

  data_process_all:
    run: r:latest analysis/R/data_process_all.R
    needs: [extract_all]
    outputs:
      highly_sensitive:
        data1: output/data/data_all.rds
        data2: output/data/data_long_vax_dates.rds
        data3: output/data/data_long_admission_dates.rds

  data_properties_all:
    run: r:latest analysis/R/data_properties.R output/data/data_all.rds output/data_properties
    needs: [data_process_all]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_all*.txt

  data_define_cohorts:
    run: r:latest analysis/R/data_define_cohorts.R
    needs: [data_process_all]
    outputs:
      highly_sensitive:
        data: output/data/data_cohorts.rds
      moderately_sensitive:
        metadata: output/data/metadata_cohorts.rds

  ## VE models in over 80s

  data_stset_over80s:
    run: r:latest analysis/R/data_stset.R over80s
    needs: [data_define_cohorts, data_process_all]
    outputs:
      highly_sensitive:
        data: output/over80s/data/data_*.rds

  data_properties_over80s:
    run: r:latest analysis/R/data_properties.R output/over80s/postest/data/data_wide.rds output/over80s/postest/data_properties
    needs: [data_stset_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/cohort/outcome/data_properties/data_wide*.txt

  descr_eventsperday_over80s:
    run: r:latest analysis/R/plot_outcomes_per_day.R over80s postest
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/over80s/postest/descr/events*.svg


  descr_table1_over80s:
    run: r:latest analysis/R/table1.R over80s
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      moderately_sensitive:
        table1: output/over80s/descr/table*

  models_msm_over80s:
    run: r:latest analysis/R/models_msms.R over80s postest
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/modes/model*.rds
        data: output/over80s/postest/models/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/weights.txt
        weightsplot: output/over80s/postest/histogram_weights.svg

  reportmodels_msm_over80s:
    run: r:latest analysis/R/reportmodels_msms.R over80s postest
    needs: [data_define_cohorts, models_msm_over80s]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/models/forest*.svg
        trend: output/over80s/postest/models/secular_trends*.svg
        eventrate: output/over80s/postest/models/event_rate.svg
        cmleffect: output/over80s/postest/models/cml_effectiveness.svg
        tables: output/over80s/postest/models/*.csv


  # data_stset_under65s:
  #   run: r:latest analysis/R/data_stset.R under65s
  #   needs: [data_cohorts, data_process_all]
  #   outputs:
  #     highly_sensitive:
  #       data: output/modeldata/data_*under65s.rds
  #
  # data_properties_under65s:
  #   run: r:latest analysis/R/data_properties.R output/modeldata/data_wide_under65s.rds output/data_properties
  #   needs: [data_stset_under65s]
  #   outputs:
  #     moderately_sensitive:
  #       datasummary: output/data_properties/data_wide_under65s*.txt
  #
  # models_msm_under65s:
  #   run: r:latest analysis/R/models_msms.R under65s
  #   needs: [data_cohorts, data_stset_under65s]
  #   outputs:
  #     moderately_sensitive:
  #       weights: output/models/msm/under65s/weights.txt
  #       forest: output/models/msm/under65s/forest*.svg
  #       trend: output/models/msm/under65s/secular_trends*.svg
  #       tables: output/models/msm/under65s/*.csv


  # models_cox_over80s:
  #   run: r:latest analysis/R/models_cox_over80s.R
  #   needs: [data_stset_over80s]
  #   outputs:
  #     moderately_sensitive:
  #       zph: output/models/cox/over80s/zph*.png
  #       forest: output/models/cox/over80s/forest*.svg
  #       tables: output/models/cox/over80s/*.csv


  # run_ve:
  #   run: cohortextractor:latest --version
  #   needs: [extract_all, data_process_all, data_properties_all, data_tte_over80s, models_cox_over80s]
  #   outputs:
  #     moderately_sensitive:
  #       whatever: output/.gitignore



