version: '3.0'

expectations:
  population_size: 100000

actions:

  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/notebooks/population_characteristics.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
  #
  #   needs: [generate_delivery_cohort]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/population_characteristics.html

  get_packages:
    run: r:latest analysis/R/export_package_names.R
    outputs:
      moderately_sensitive:
        cohort: output/available_packages.csv



## Descriptive info on vaccinated patients

  extract_vaccinated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vaccinated
    outputs:
      highly_sensitive:
        cohort: output/input_vaccinated.csv

  data_process_vaccinated:
    run: r:latest analysis/R/data_process_vaccinated.R
    needs: [extract_vaccinated]
    outputs:
      highly_sensitive:
        cohort: output/data/data_vaccinated.rds
        vaxdates: output/data/data_vaccinated_vax_dates.rds

  data_properties_vaccinated:
    run: r:latest analysis/R/data_properties.R output/data/data_vaccinated.rds output/data_properties
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        summary: output/data_properties/data_vaccinated*.txt

  data_summarise_vaccinated:
    run: r:latest analysis/R/data_summarise.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        summary1: output/variable_summary/categorical.txt
        summary2: output/variable_summary/numeric.txt
        summary3: output/variable_summary/date.txt
        summarytables: output/variable_summary/tables/categorical_*.csv
        summarystats: output/summary_stats.json

  vaccine_tables:
    run: r:latest analysis/R/vaccine_type.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        tables: output/vaccine_type/tables/vaccine_type_*.csv

  tte_tables:
    run: r:latest analysis/R/tte_tables.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        tables: output/tte/tables/event_rates_*.csv

  tte_plots:
    run: r:latest analysis/R/tte_plots.R
    needs: [data_process_vaccinated]
    outputs:
      moderately_sensitive:
        plots: output/tte/figures/plot_*.svg



  # data for whole cohort

  extract_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all
    outputs:
      highly_sensitive:
        cohort: output/input_all.csv


  data_process_all:
    run: r:latest analysis/R/data_process_all.R
    needs: [extract_all]
    outputs:
      highly_sensitive:
        data1: output/data/data_all.rds
        data2: output/data/data_long_vax_dates.rds
        data3: output/data/data_long_admission_dates.rds

  data_properties_all:
    run: r:latest analysis/R/data_properties.R output/data/data_all.rds output/data_properties
    needs: [data_process_all]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_all*.txt


  ## VE models in over 80s

  data_tte_over80s:
    run: r:latest analysis/R/data_tte_over80s.R
    needs: [data_process_all]
    outputs:
      highly_sensitive:
        data: output/modeldata/data_tte_*.rds

  data_properties_over80s:
    run: r:latest analysis/R/data_properties.R output/modeldata/data_tte_over80s.rds output/data_properties
    needs: [data_tte_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_tte_over80s*.txt

  models_cox_over80s:
    run: r:latest analysis/R/models_cox_over80s.R
    needs: [data_tte_over80s]
    outputs:
      moderately_sensitive:
        zph: output/models/cox/over80s/zph*.png
        forest: output/models/cox/over80s/forest*.svg
        tables: output/models/cox/over80s/*.csv

  models_msm_over80s:
    run: r:latest analysis/R/models_msm_over80s.R
    needs: [data_tte_over80s]
    outputs:
      moderately_sensitive:
        weights: output/models/msm/over80s/weights.txt
        forest: output/models/msm/over80s/forest*.svg
        #trend: output/models/msm/over80s/secular_trends*.svg
        tables: output/models/msm/over80s/*.csv


  # run_ve:
  #   run: cohortextractor:latest --version
  #   needs: [extract_all, data_process_all, data_properties_all, data_tte_over80s, models_cox_over80s]
  #   outputs:
  #     moderately_sensitive:
  #       whatever: output/.gitignore

  # models_under65s:
  #   run: r:latest analysis/R/models_under65s.R
  #   needs: [data_process_all]
  #   outputs:
  #     moderately_sensitive:
  #       #datasummary: output/data_properties/data_tte_over80s*.txt
  #       zph: output/models/under65s/zph*.png
  #       forest: output/models/under65s/forest*.svg
  #       tables: output/models/under65s/*.csv



