version: '3.0'

expectations:
  population_size: 1000000

actions:

  extract_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_all
    outputs:
      highly_sensitive:
        cohort: output/input_all.csv

  data_process_all:
    run: r:latest analysis/R/data_process_all.R
    needs: [extract_all]
    outputs:
      highly_sensitive:
        data1: output/data/data_all.rds
        data2: output/data/data_long_vax_dates.rds
        data3: output/data/data_long_admission_dates.rds
        data4: output/data/data_long_pr_probable_covid_dates.rds
        data5: output/data/data_long_pr_suspected_covid_dates.rds


  data_properties_all:
    run: r:latest analysis/R/data_properties.R output/data/data_all.rds output/data_properties
    needs: [data_process_all]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_all*.txt

  data_define_cohorts:
    run: r:latest analysis/R/data_define_cohorts.R
    needs: [data_process_all]
    outputs:
      highly_sensitive:
        data: output/data/data_cohorts.rds
      moderately_sensitive:
        metadata: output/data/metadata_cohorts.rds
        formula: output/data/list_formula.rds



#######################################
#######################################
  ## VE in over 80s (over80s)
#######################################
#######################################

  data_stset_over80s:
    run: r:latest analysis/R/data_stset.R over80s
    needs: [data_define_cohorts, data_process_all]
    outputs:
      highly_sensitive:
        data: output/over80s/data/data_*.rds

  data_properties_over80s_fixed:
    run: r:latest analysis/R/data_properties.R output/over80s/data/data_wide_fixed.rds output/over80s/data_properties
    needs: [data_stset_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/over80s/data_properties/data_wide_fixed*.txt

  data_properties_over80s_tte:
    run: r:latest analysis/R/data_properties.R output/over80s/data/data_wide_tte.rds output/over80s/data_properties
    needs: [data_stset_over80s]
    outputs:
      moderately_sensitive:
        datasummary: output/over80s/data_properties/data_wide_tte*.txt

  # descr_eventsperday_over80s:
  #   run: r:latest analysis/R/plot_outcomes_per_day.R over80s postest
  #   needs: [data_define_cohorts, data_stset_over80s]
  #   outputs:
  #     moderately_sensitive:
  #       datasummary: output/over80s/postest/descr/events*.svg

  descr_table1_over80s:
    run: r:latest analysis/R/table1.R over80s
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      moderately_sensitive:
        table1: output/over80s/descr/tables/table*

  descr_events_over80s:
    run: r:latest analysis/R/plot_status_over_time.R over80s
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      moderately_sensitive:
        plots: output/over80s/descr/plots/*.svg

#######################################
 ## MODELS: vax1 only (ignores second dose)
#######################################

## any vaccine

  models_msm_over80s_any_dose1:
    run: r:latest analysis/R/models_msms_dose1.R over80s postest any
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/any/dose1/model*.rds
        data: output/over80s/postest/any/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/any/dose1/weights.txt
        weightsplot: output/over80s/postest/any/dose1/histogram_weights.svg

  reportmodels_msm_over80s_any_dose1:
    run: r:latest analysis/R/reportmodels_msms_dose1.R over80s postest any
    needs: [data_define_cohorts, models_msm_over80s_any_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/any/dose1/forest*.svg
        trend: output/over80s/postest/any/dose1/secular_trends*.svg
        tables: output/over80s/postest/any/dose1/*.csv


## pfizer vaccine
  models_msm_over80s_pfizer_dose1:
    run: r:latest analysis/R/models_msms_dose1.R over80s postest pfizer
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/pfizer/dose1/model*.rds
        data: output/over80s/postest/pfizer/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/pfizer/dose1/weights.txt
        weightsplot: output/over80s/postest/pfizer/dose1/histogram_weights.svg

  reportmodels_msm_over80s_pfizer_dose1:
    run: r:latest analysis/R/reportmodels_msms_dose1.R over80s postest pfizer
    needs: [data_define_cohorts, models_msm_over80s_pfizer_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/pfizer/dose1/forest*.svg
        trend: output/over80s/postest/pfizer/dose1/secular_trends*.svg
        tables: output/over80s/postest/pfizer/dose1/*.csv


## az vaccine

  models_msm_over80s_az_dose1:
    run: r:latest analysis/R/models_msms_dose1.R over80s postest az
    needs: [data_define_cohorts, data_stset_over80s]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/az/dose1/model*.rds
        data: output/over80s/postest/az/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/az/dose1/weights.txt
        weightsplot: output/over80s/postest/az/dose1/histogram_weights.svg

  reportmodels_msm_over80s_az_dose1:
    run: r:latest analysis/R/reportmodels_msms_dose1.R over80s postest az
    needs: [data_define_cohorts, models_msm_over80s_az_dose1]
    outputs:
      moderately_sensitive:
        forest: output/over80s/postest/az/dose1/forest*.svg
        trend: output/over80s/postest/az/dose1/secular_trends*.svg
        tables: output/over80s/postest/az/dose1/*.csv



#######################################
## SUBGROUPS
#######################################

## sex

  models_msm_over80s_any_sex_dose1:
    run: r:latest analysis/R/models_msms_subgroup_dose1.R over80s postest any sex
    needs: [data_define_cohorts, data_stset_over80s, models_msm_over80s_any_dose1]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/any/sex/dose1/model*.rds
        data: output/over80s/postest/any/sex/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/any/sex/dose1/weights.txt
        weightsplot: output/over80s/postest/any/sex/dose1/histogram_weights.svg

  models_msm_over80s_pfizer_sex_dose1:
    run: r:latest analysis/R/models_msms_subgroup_dose1.R over80s postest pfizer sex
    needs: [data_define_cohorts, data_stset_over80s, models_msm_over80s_pfizer_dose1]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/pfizer/sex/dose1/model*.rds
        data: output/over80s/postest/pfizer/sex/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/pfizer/sex/dose1/weights.txt
        weightsplot: output/over80s/postest/pfizer/sex/dose1/histogram_weights.svg

  models_msm_over80s_az_sex_dose1:
    run: r:latest analysis/R/models_msms_subgroup_dose1.R over80s postest az sex
    needs: [data_define_cohorts, data_stset_over80s, models_msm_over80s_az_dose1]
    outputs:
      highly_sensitive:
        models: output/over80s/postest/az/sex/dose1/model*.rds
        data: output/over80s/postest/az/sex/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/over80s/postest/az/sex/dose1/weights.txt
        weightsplot: output/over80s/postest/az/sex/dose1/histogram_weights.svg






#######################################
#######################################
  ## VE in 70s (in70s)
#######################################
#######################################

  data_stset_in70s:
    run: r:latest analysis/R/data_stset.R in70s
    needs: [data_define_cohorts, data_process_all]
    outputs:
      highly_sensitive:
        data: output/in70s/data/data_*.rds

  data_properties_in70s_fixed:
    run: r:latest analysis/R/data_properties.R output/in70s/data/data_wide_fixed.rds output/in70s/data_properties
    needs: [data_stset_in70s]
    outputs:
      moderately_sensitive:
        datasummary: output/in70s/data_properties/data_wide_fixed*.txt

  data_properties_in70s_tte:
    run: r:latest analysis/R/data_properties.R output/in70s/data/data_wide_tte.rds output/in70s/data_properties
    needs: [data_stset_in70s]
    outputs:
      moderately_sensitive:
        datasummary: output/in70s/data_properties/data_wide_tte*.txt

  # descr_eventsperday_in70s:
  #   run: r:latest analysis/R/plot_outcomes_per_day.R in70s postest
  #   needs: [data_define_cohorts, data_stset_in70s]
  #   outputs:
  #     moderately_sensitive:
  #       datasummary: output/in70s/postest/descr/events*.svg

  descr_table1_in70s:
    run: r:latest analysis/R/table1.R in70s
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      moderately_sensitive:
        table1: output/in70s/descr/tables/table*

  descr_events_in70s:
    run: r:latest analysis/R/plot_status_over_time.R in70s
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      moderately_sensitive:
        plots: output/in70s/descr/plots/*.svg

#######################################
 ## MODELS: vax1 only (ignores second dose)
#######################################

  models_msm_in70s_any_dose1:
    run: r:latest analysis/R/models_msms_dose1.R in70s postest any
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/any/dose1/model*.rds
        data: output/in70s/postest/any/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/in70s/postest/any/dose1/weights.txt
        weightsplot: output/in70s/postest/any/dose1/histogram_weights.svg

  reportmodels_msm_in70s_any_dose1:
    run: r:latest analysis/R/reportmodels_msms_dose1.R in70s postest any
    needs: [data_define_cohorts, models_msm_in70s_any_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/any/dose1/forest*.svg
        trend: output/in70s/postest/any/dose1/secular_trends*.svg
        tables: output/in70s/postest/any/dose1/*.csv

  models_msm_in70s_pfizer_dose1:
    run: r:latest analysis/R/models_msms_dose1.R in70s postest pfizer
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/pfizer/dose1/model*.rds
        data: output/in70s/postest/pfizer/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/in70s/postest/pfizer/dose1/weights.txt
        weightsplot: output/in70s/postest/pfizer/dose1/histogram_weights.svg

  reportmodels_msm_in70s_pfizer_dose1:
    run: r:latest analysis/R/reportmodels_msms_dose1.R in70s postest pfizer
    needs: [data_define_cohorts, models_msm_in70s_pfizer_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/pfizer/dose1/forest*.svg
        trend: output/in70s/postest/pfizer/dose1/secular_trends*.svg
        tables: output/in70s/postest/pfizer/dose1/*.csv

  models_msm_in70s_az_dose1:
    run: r:latest analysis/R/models_msms_dose1.R in70s postest az
    needs: [data_define_cohorts, data_stset_in70s]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/az/dose1/model*.rds
        data: output/in70s/postest/az/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/in70s/postest/az/dose1/weights.txt
        weightsplot: output/in70s/postest/az/dose1/histogram_weights.svg

  reportmodels_msm_in70s_az_dose1:
    run: r:latest analysis/R/reportmodels_msms_dose1.R in70s postest az
    needs: [data_define_cohorts, models_msm_in70s_az_dose1]
    outputs:
      moderately_sensitive:
        forest: output/in70s/postest/az/dose1/forest*.svg
        trend: output/in70s/postest/az/dose1/secular_trends*.svg
        tables: output/in70s/postest/az/dose1/*.csv



#######################################
## SUBGROUPS
#######################################

## sex


  models_msm_in70s_any_sex_dose1:
    run: r:latest analysis/R/models_msms_subgroup_dose1.R in70s postest any sex
    needs: [data_define_cohorts, data_stset_in70s, models_msm_in70s_any_dose1]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/any/sex/dose1/model*.rds
        data: output/in70s/postest/any/sex/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/in70s/postest/any/sex/dose1/weights.txt
        weightsplot: output/in70s/postest/any/sex/dose1/histogram_weights.svg

  models_msm_in70s_pfizer_sex_dose1:
    run: r:latest analysis/R/models_msms_subgroup_dose1.R in70s postest pfizer sex
    needs: [data_define_cohorts, data_stset_in70s, models_msm_in70s_pfizer_dose1]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/pfizer/sex/dose1/model*.rds
        data: output/in70s/postest/pfizer/sex/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/in70s/postest/pfizer/sex/dose1/weights.txt
        weightsplot: output/in70s/postest/pfizer/sex/dose1/histogram_weights.svg

  models_msm_in70s_az_sex_dose1:
    run: r:latest analysis/R/models_msms_subgroup_dose1.R in70s postest az sex
    needs: [data_define_cohorts, data_stset_in70s, models_msm_in70s_az_dose1]
    outputs:
      highly_sensitive:
        models: output/in70s/postest/az/sex/dose1/model*.rds
        data: output/in70s/postest/az/sex/dose1/data_weights.rds
      moderately_sensitive:
        weights: output/in70s/postest/az/sex/dose1/weights.txt
        weightsplot: output/in70s/postest/az/sex/dose1/histogram_weights.svg







 # vax1 and vax2
#
#   models_msm_over80s_any_dose12:
#     run: r:latest analysis/R/models_msms_dose12.R over80s postest any
#     needs: [data_define_cohorts, data_stset_over80s]
#     outputs:
#       highly_sensitive:
#         models: output/over80s/postest/any/dose12/model*.rds
#         data: output/over80s/postest/any/dose12/data_weights.rds
#       moderately_sensitive:
#         weights: output/over80s/postest/any/dose12/weights.txt
#         weightsplot: output/over80s/postest/any/dose12/histogram_weights.svg
#
#   reportmodels_msm_over80s_any_dose12:
#     run: r:latest analysis/R/reportmodels_msms_dose12.R over80s postest any
#     needs: [data_define_cohorts, models_msm_over80s_any_dose12]
#     outputs:
#       moderately_sensitive:
#         forest: output/over80s/postest/any/dose12/forest*.svg
#         trend: output/over80s/postest/any/dose12/secular_trends*.svg
#         tables: output/over80s/postest/any/dose12/*.csv
#
#
#   models_msm_over80s_pfizer_dose12:
#     run: r:latest analysis/R/models_msms_dose12.R over80s postest pfizer
#     needs: [data_define_cohorts, data_stset_over80s]
#     outputs:
#       highly_sensitive:
#         models: output/over80s/postest/pfizer/dose12/model*.rds
#         data: output/over80s/postest/pfizer/dose12/data_weights.rds
#       moderately_sensitive:
#         weights: output/over80s/postest/pfizer/dose12/weights.txt
#         weightsplot: output/over80s/postest/pfizer/dose12/histogram_weights.svg
#
#   reportmodels_msm_over80s_pfizer_dose12:
#     run: r:latest analysis/R/reportmodels_msms_dose12.R over80s postest pfizer
#     needs: [data_define_cohorts, models_msm_over80s_pfizer_dose12]
#     outputs:
#       moderately_sensitive:
#         forest: output/over80s/postest/pfizer/dose12/forest*.svg
#         trend: output/over80s/postest/pfizer/dose12/secular_trends*.svg
#         tables: output/over80s/postest/pfizer/dose12/*.csv
#
#
#   models_msm_over80s_az_dose12:
#     run: r:latest analysis/R/models_msms_dose12.R over80s postest az
#     needs: [data_define_cohorts, data_stset_over80s]
#     outputs:
#       highly_sensitive:
#         models: output/over80s/postest/az/dose12/model*.rds
#         data: output/over80s/postest/az/dose12/data_weights.rds
#       moderately_sensitive:
#         weights: output/over80s/postest/az/dose12/weights.txt
#         weightsplot: output/over80s/postest/az/dose12/histogram_weights.svg
#
#   reportmodels_msm_over80s_az_dose12:
#     run: r:latest analysis/R/reportmodels_msms_dose12.R over80s postest az
#     needs: [data_define_cohorts, models_msm_over80s_az_dose12]
#     outputs:
#       moderately_sensitive:
#         forest: output/over80s/postest/az/dose12/forest*.svg
#         trend: output/over80s/postest/az/dose12/secular_trends*.svg
#         tables: output/over80s/postest/az/dose12/*.csv


